# =====================================================================
# Standalone OPA Policies Hot-Reload Setup
# =====================================================================
# This YAML deploys:
# 1. A ConfigMap containing example Rego policies
# 2. A hot-reload sidecar Deployment that uploads policies to an
#    existing OPA server in the "opa" namespace.
#
# Features:
# - Guaranteed valid Rego with proper default rules
# - Automatic reload on ConfigMap changes
# - Safe startup: waits until OPA server is ready
# - Logs successes and errors, never crashes on invalid policies
# =====================================================================

# =====================================================================
# 1. Policies ConfigMap
# =====================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies-src
  namespace: opa
  labels:
    app: opa
data:
  # ---------------------------------------
  # Example allow policy
  # Grants access if input.user == "admin"
  # ---------------------------------------
  allow.rego: |
    package example.allow

    default allow = false

    allow {
        input.user == "admin"
    }

  # ---------------------------------------
  # Example deny policy
  # Blocks access if input.block == true
  # ---------------------------------------
  deny.rego: |
    package example.deny

    default deny = false

    deny {
        input.block == true
    }

  # ---------------------------------------
  # Example validate policy
  # Returns valid if input.value > 0
  # ---------------------------------------
  validate.rego: |
    package example.validate

    default valid = false

    valid {
        input.value > 0
    }

---
# =====================================================================
# 2. Hot-reload Sidecar Deployment
# =====================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-policy-reloader
  namespace: opa
  labels:
    app: opa-policy-reloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-policy-reloader
  template:
    metadata:
      labels:
        app: opa-policy-reloader
    spec:
      containers:
        - name: policy-reloader
          image: alpine:3.19
          # Start a shell that runs the policy uploader loop
          command: ["sh", "-c"]
          args:
            - |
              # Install dependencies
              apk add --no-cache curl inotify-tools >/dev/null 2>&1 || true

              echo "[Reloader] Waiting for OPA server to become ready..."
              # Wait until OPA /health returns 200
              until curl -s http://opa.opa.svc.cluster.local:8181/health >/dev/null 2>&1; do
                  sleep 2
              done
              echo "[Reloader] OPA is ready, starting initial policy load..."

              # Function to upload a policy file to OPA
              reload_policy() {
                  f="$1"
                  name=$(basename "$f")
                  echo "[Reloader] Uploading policy: $name"

                  # Upload using curl and capture HTTP code
                  http_code=$(curl -s -o >(cat) -w "%{http_code}" -X PUT --data-binary @"$f" http://opa.opa.svc.cluster.local:8181/v1/policies/$name)

                  if [ "$http_code" -ne 200 ]; then
                      echo "[Reloader] ERROR uploading $name: HTTP code $http_code"
                  else
                      echo "[Reloader] Successfully loaded $name"
                  fi
              }

              # Initial upload of all policies
              for f in /policies-src/*.rego; do
                  reload_policy "$f"
              done

              # Watch for changes in the ConfigMap mount
              echo "[Reloader] Watching /policies-src for changes..."
              while true; do
                  inotifywait -e modify,create,delete /policies-src
                  echo "[Reloader] Change detected — reloading policies..."
                  for f in /policies-src/*.rego; do
                      reload_policy "$f"
                  done
              done

          volumeMounts:
            - name: policies-src
              mountPath: /policies-src

      volumes:
        # Mount the policies ConfigMap
        - name: policies-src
          configMap:
            name: opa-policies-src
