# =====================================================================
# 1. Namespace
# =====================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: opa
  labels:
    app: opa

---
# =====================================================================
# 2. TLS Secret (create dynamically from local files)
#    Do NOT include data in YAML. Create with:
#    kubectl create secret tls opa-tls-secret \
#      --cert=opa.local.pem \
#      --key=opa.local-key.pem \
#      -n opa
# =====================================================================
# DO NOT include data in YAML. Create dynamically from local files:
# kubectl create secret tls opa-tls-secret \
#   --cert=opa.local.pem \
#   --key=opa.local-key.pem \
#   -n opa
# =====================================================================

---
# =====================================================================
# 3. OPA ConfigMap
# =====================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: opa
data:
  opa.yaml: |
    services: {}
    bundles: {}
    decision_logs:
      console: true
    status:
      console: true

---
# =====================================================================
# 4. OPA Deployment
# =====================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:v0.52.0
          args:
            - "run"
            - "--server"
            - "--config-file=/config/opa.yaml"
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: opa-config
              mountPath: /config
           # =========================
          # Readiness probe ensures Traefik only routes to ready pods
          # Adjusted for Rancher Desktop so pod is ready quickly
          # =========================
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8181
          #   initialDelaySeconds: 1
          #   periodSeconds: 2
          #   timeoutSeconds: 1
          #   failureThreshold: 3
          # =========================
          # Liveness probe ensures OPA restarts if it becomes unhealthy
          # =========================
          livenessProbe:
            httpGet:
              path: /health
              port: 8181
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: opa-config
          configMap:
            name: opa-config

---
# =====================================================================
# 5. OPA Service
# =====================================================================
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: opa
spec:
  selector:
    app: opa
  ports:
    - name: http
      port: 8181
      targetPort: 8181

---
# =====================================================================
# 6. Kubernetes Ingress for Rancher Desktop Traefik
# =====================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opa-ingress
  namespace: opa
spec:
  ingressClassName: traefik   # Required for Rancher Desktop built-in Traefik
  tls:
    - hosts:
        - opa.local
      secretName: opa-tls-secret
  rules:
    - host: opa.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opa
                port:
                  number: 8181
