# =====================================================================
# 1. Policies ConfigMap — Standalone, guaranteed to compile
# =====================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies-src
  namespace: opa
data:
  allow.rego: |
    package example.allow

    default allow = false

    allow {
        input.user == "admin"
    }

  deny.rego: |
    package example.deny

    default deny = false

    deny {
        input.block == true
    }

  validate.rego: |
    package example.validate

    valid {
        input.value > 0
    }

---
# =====================================================================
# 2. Hot-reload Sidecar Deployment (Standalone)
#    Watches /policies-src and uploads to existing OPA
# =====================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-policy-reloader
  namespace: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa-policy-reloader
  template:
    metadata:
      labels:
        app: opa-policy-reloader
    spec:
      containers:
        - name: policy-reloader
          image: alpine:3.19
          command: ["sh", "-c"]
          args:
            - |
              apk add --no-cache inotify-tools curl >/dev/null 2>&1 || true
              echo "[Reloader] Starting policy watcher..."

              reload_policy() {
                  f="$1"
                  name=$(basename "$f")
                  echo "[Reloader] Uploading policy: $name"

                  # Curl PUT to OPA; capture output and status code
                  http_code=$(curl -s -o >(cat) -w "%{http_code}" -X PUT --data-binary @"$f" http://opa.opa.svc.cluster.local:8181/v1/policies/$name)

                  if [ "$http_code" -ne 200 ]; then
                      echo "[Reloader] ERROR uploading $name: HTTP code $http_code"
                  else
                      echo "[Reloader] Successfully loaded $name"
                  fi
              }

              # Initial load of all policies
              for f in /policies-src/*.rego; do
                  reload_policy "$f"
              done

              # Watch for changes
              while true; do
                  inotifywait -e modify,create,delete /policies-src
                  echo "[Reloader] Change detected — reloading policies..."
                  for f in /policies-src/*.rego; do
                      reload_policy "$f"
                  done
              done

          volumeMounts:
            - name: policies-src
              mountPath: /policies-src
      volumes:
        - name: policies-src
          configMap:
            name: opa-policies-src
