# =====================================================================
# 1. Namespace for OPA
# =====================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: opa
  labels:
    app: opa

---
# =====================================================================
# 2. OPA ConfigMap
# =====================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: opa
data:
  opa.yaml: |
    services: {}
    bundles: {}
    decision_logs:
      console: true
    status:
      console: true

---
# =====================================================================
# 3. OPA Deployment
# =====================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--config-file=/config/opa.yaml"
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: opa-config
              mountPath: /config
      volumes:
        - name: opa-config
          configMap:
            name: opa-config

---
# =====================================================================
# 4. OPA Service
# =====================================================================
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: opa
spec:
  selector:
    app: opa
  ports:
    - name: http
      port: 8181
      targetPort: 8181

---
# =====================================================================
# 5. Kubernetes Ingress for Rancher Desktop Traefik
# =====================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opa-ingress
  namespace: opa
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - opa.local
      secretName: opa-tls-secret
  rules:
    - host: opa.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opa
                port:
                  number: 8181
